name: "Multi event pipeline / workflow" # Name of the pipeline
on: 
   push: # Event: Whenever a push is made to the repository on the master branch
       branches: 
            - master
            - test
   pull_request: # Event: Whenever a pull request is made to this repository
      branches:
          - master
      types:
          - closed
   workflow_dispatch:

jobs: # jobs
    on-push:
        if: github.event_name == 'push'
        runs-on: ubuntu-latest
        steps: # Steps to be executed in the job
          - name: "Running on master/test push"
            run: echo "Running on master/test push"

    on-pull-request: 
        if: github.event_name == 'pull_request'
        runs-on: ubuntu-latest
        steps: 
          - name: "Running on pull request"
            run: echo "Running on pull request"

    on-pull-request-closed:
      if: github.event_name == 'pull_request' && github.event_name == 'closed'
      runs-on: ubuntu-latest
      steps:
          - name: "Running on pull request closed"
            run: echo "Running on pull request closed"
    
    on-workflow_dispatch: 
      if: github.event_name == 'workflow_dispatch'
      runs-on: ubuntu-latest
      steps: 
          - name: "Running on workflow dispatch"
            run: echo "Running on workflow dispatch"